include:
  - project: 'ccx/ccx-gitlab-includes'
    file: '/ccx-lib.yml'


linting:
  extends:
    - .pre-commit:lint


pre-commit-autoupdate-check:
  extends:
    - .pre-commit:autoupdate-check


pre-commit-autoupdate:
  extends: .pre-commit:autoupdate
  rules:
  - if: $CI_PIPELINE_SOURCE == "schedule"
  variables:
    MAINTAINERS: "@jipapous"
