repos:
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.13.0
    hooks:
      - id: reorder-python-imports
        language_version: python3
        args:
          - --application-directories=.:server
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        args: [--safe, --quiet, --line-length, "100"]
        language_version: python3
        require_serial: true
  - repo: https://github.com/PyCQA/flake8.git
    rev: 7.0.0
    hooks:
      - id: flake8
        language_version: python3
        args:
          - --max-line-length=100
          - --ignore=W503,E203
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        language_version: python3
      - id: end-of-file-fixer
        language_version: python3
      - id: debug-statements
        language_version: python3
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.16.0
    hooks:
      - id: pyupgrade
        language_version: python3
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        additional_dependencies:
          - types-PyYAML
          - types-requests
