name: Linters
on:
  - push
  - pull_request

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1

  pre-commit-flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
            python-version: '3.12'
      - uses: pre-commit/action@v3.0.1
        with:
          extra_args: flake8 --all-files

  pre-commit-pyupgrade:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-python@v5
          with:
              python-version: '3.12'
        - uses: pre-commit/action@v3.0.1
          with:
            extra_args: pyupgrade --all-files

  pre-commit-black:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-python@v5
          with:
              python-version: '3.12'
        - uses: pre-commit/action@v3.0.1
          with:
            extra_args: black --all-files

  pre-commit-debug-statements:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-python@v5
          with:
              python-version: '3.12'
        - uses: pre-commit/action@v3.0.1
          with:
            extra_args: debug-statements --all-files

  pre-commit-mypy:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-python@v5
          with:
              python-version: '3.12'
        - uses: pre-commit/action@v3.0.1
          with:
            extra_args: mypy --all-files

  pre-commit-trailing-whitespace:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-python@v5
          with:
              python-version: '3.12'
        - uses: pre-commit/action@v3.0.1
          with:
            extra_args: trailing-whitespace --all-files

  pre-commit-end-of-file-fixer:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-python@v5
          with:
              python-version: '3.12'
        - uses: pre-commit/action@v3.0.1
          with:
            extra_args: end-of-file-fixer --all-files

  pre-commit-reorder-python-imports:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-python@v5
          with:
              python-version: '3.12'
        - uses: pre-commit/action@v3.0.1
          with:
            extra_args: reorder-python-imports --all-files
